source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
target 'Afterparty' do
  pod 'Foursquare-API-v2', '~> 1.4'
  pod 'SVProgressHUD' 
  pod 'TTTAttributedLabel', '~> 1.10'
  pod 'pop', '~> 1.0'
  pod 'Parse', '~> 1.14'
  pod 'AFNetworking'
  pod 'ParseFacebookUtils', '~> 1.10'
  pod "JazzHands"
  pod 'ParseTwitterUtils', '~> 1.11'
end
